// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqN10acOG0qTP3FJn2jffdm3sjRplY5NM',
    appId: '1:686503363477:web:3a8ddbe15de8039853ec9c',
    messagingSenderId: '686503363477',
    projectId: 'maketheproject-f7f9e',
    authDomain: "maketheproject-f7f9e.firebaseapp.com",
    storageBucket: 'maketheproject-f7f9e.appspot.com',
    measurementId: 'G-61VBCB0QV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKomNe0K_yUZptipXUcPD0n6ujnqMpTfQ',
    appId: '1:686503363477:android:9e46991ff8d19b8153ec9c',
    messagingSenderId: '686503363477',
    projectId: 'maketheproject-f7f9e',
    storageBucket: 'maketheproject-f7f9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ0G9PCdskrHcWJj3ujcbp_jC19xiebzI',
    appId: '1:686503363477:ios:1f96f2338a9ade7b53ec9c',
    messagingSenderId: '686503363477',
    projectId: 'maketheproject-f7f9e',
    storageBucket: 'maketheproject-f7f9e.appspot.com',
    iosClientId: '686503363477-0cpb5nk24l48m85rnigo5jchi3chrl9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.isprouts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ0G9PCdskrHcWJj3ujcbp_jC19xiebzI',
    appId: '1:686503363477:ios:1f96f2338a9ade7b53ec9c',
    messagingSenderId: '686503363477',
    projectId: 'maketheproject-f7f9e',
    storageBucket: 'maketheproject-f7f9e.appspot.com',
    iosClientId: '686503363477-0cpb5nk24l48m85rnigo5jchi3chrl9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.isprouts',
  );
}
